# Generated by Django 5.2.6 on 2025-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='period',
            field=models.CharField(choices=[('1', 'الأولى'), ('2', 'الثانية'), ('3', 'الثالثة'), ('4', 'الرابعة'), ('5', 'الخامسة'), ('6', 'السادسة'), ('7', 'السابعة')], max_length=1),
        ),
    ]
